name: FastAPI CI/CD

on:
  push:
    branches:
      - main  # Chạy khi có push vào nhánh chính
  pull_request:
    branches:
      - main  # Chạy khi có pull request vào nhánh chính

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Sử dụng runner của GitHub Actions là Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout mã nguồn

    # - name: Build Docker image
    #   run: |
    #     docker build -t api_lp_ocr:latest .  # Build Docker image từ Dockerfile trong repo

    - name: Deploy to local Ubuntu machine
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key trong GitHub Secrets
        LOCAL_UBUNTU_USER: "codespace"  # Username trên máy Ubuntu của bạn
        LOCAL_UBUNTU_IP: "127.0.0.1"  # Địa chỉ IP local của máy Ubuntu (127.0.0.1 nếu là máy local)
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        ssh -i private_key.pem -o StrictHostKeyChecking=no $LOCAL_UBUNTU_USER@$LOCAL_UBUNTU_IP << 'EOF'
          cd /home/duyhv/Documents/AI/lpr_api

          docker build -t api_lp_ocr:latest .

          docker-compose down
          
          docker-compose up -d
        EOF
